-- Start of DDL Script for View MARMORE.VPROD
-- Generated 19-set-2024 10:37:32 from MARMORE@192.168.0.163:1521/orcl

CREATE OR REPLACE VIEW vprod (
   descricao,
   codbarra,
   pvenda )
AS
SELECT PRODUTO.DESCRICAO, PRODUTO.CODBARRA, EMBALAGEM.PVENDA

FROM PRODUTO, EMBALAGEM

WHERE PRODUTO.CODPROD = EMBALAGEM.CODPROD
/


-- End of DDL Script for View MARMORE.VPROD

